### PR TITLE
Improve print to file and improve tests

### PR DESCRIPTION
**Pull request by Vovan707**
Make swap of object to outpout to very easy and  escape file (path) dependency in menu

### CODE REVIEW

**Comment by Vovan707** [comment]
@sergeyradkevich  review please

**Comment by sergeyradkevich** [comment]
@Vovan707 Please rebase.

**Comment by sergeyradkevich** [comment]
Hey @Vovan707 Do you remember a good rule to leave a text comment to let others know why the PR has been closed? I suggest always leave a short note about the reason.

**Comment by Vovan707** [comment]
@sergeyradkevich  sorry, I was forgot(

**Comment by sergeyradkevich** [comment]
@Vovan707 That was a reminder ;)

**Pull request closed without merging**
