### PR TITLE
Replace tab on space

### PR DESCRIPTION
**Pull request by Vovan707**
Replace tab on space on IDE and refactored code

### CODE REVIEW

**Comment by Vovan707** [comment]
@sergeyradkevich  review please

**Comment by sergeyradkevich** [comment]
@Vovan707 Formatting looks fine :+1: Let's use such formatting rules for the future development.

**Comment by sergeyradkevich** [comment]
@Vovan707 Please update status in the documents for tasks.

**Comment by Vovan707** [comment]
@sergeyradkevich  Ok)

**Pull request merged**
